### ISSUE TITLE
macros within macros fails ?

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [datatrash/mos#168]
```

.macro MA(value) {
	ldx #value 
}

.macro MB(value) {
	MA(32)
	ldy #value
}

MB(64)

```
.. expect .. 
```

ldx #32
ldy #64  

```
.. result .. 
`
ldy #64`

**Comment by sagacity** [comment]
It turns it out this is a symbol resolution issue. When you are inside `MB` and then call `MA`, then `MB.MA` will become a scope (so you could, in theory, refer to any labels that were created in `MB.MA`).

However, when looking up the macro definition (which is `MA`, on the root scope), it will actually try to pick up `MB.MA` as the macro definition instead, since that's locally in scope in `MB`. Anyway. Doesn't work, because a scope definition isn't a macro definition.

tl;dr I'll fix it :)
