### ISSUE TITLE
mos allows addressing modes that don't exist

### ISSUE THREAD

**Issue by kebby** [datatrash/mos#193]
Trying invalid addressing modes, like `ldx $1234,x` or `inc #$12` doesn't result in an error but assembles to... something (haven't looked into the output). This shouldn't really be allowed.

**Comment by sagacity** [comment]
Hmm, I'm fairly certain it won't be emitting something since there are no valid opcodes to pick from. It's odd no error is generated of course, I'll take a look.

**Comment by sagacity** [comment]
Ah, this is caused by some code that was added when implementing code completion. When doing code completion I _do_ want broken stuff to assemble (so that I can give you valid symbols after you've typed `lda ` for instance, which by itself is not a valid instruction), but of course this very lenient mode should not be enabled otherwise.
